#!/bin/bash

#set -x

. version
./mktar

tmp=$PWD/$$
trap "/bin/rm -rf $tmp" 0

mkdir -p $tmp
cd $tmp || (echo "Cannot cd $tmp"; exit 1)

mkdir BUILD/ BUILDROOT/ RPMS/ SOURCES/ SPECS/ SRPMS/
cp ../$tar SOURCES
cp ../${name}.spec SPECS

rpmbuild --define "_topdir $PWD" -ba SPECS/${name}.spec
mv RPMS/*/*rpm ..
mv SRPMS/*rpm ..
